variables:
  DIR: frontend/matchify
  APP_NAME: matchify-frontend
  APP_PORT: 3000
  APP_DIR: ./frontend/matchify
  APP_CONTAINER_NAME: matchify-frontend-app

image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - $DIR/node_modules/
  - $DIR/.next/

stages:
  - build
  - test
  - quality
  - publish
  - deploy

build:
  stage: build
  script:
    - cd $APP_DIR
    - npm ci

test:
  stage: test
  script:
    - cd $APP_DIR
    - npm run test

quality:
  stage: quality
  trigger:
    include:
      - template: Code-Quality.gitlab-ci.yml
  only:
    - dev
    - main

publish:
  image: docker:latest
  stage: publish
  tags:
    - deployment  
  variables:
    # these values may need to be different if using TLS, k8s, etc.
    # You can alternatively set defaults in your runner config
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  script:
    - cd $APP_DIR
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - docker build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL -t docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA
  environment:
    name: production
  only:
    - main

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment  
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - apk update && apk add openssh-client
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA"
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $APP_CONTAINER_NAME 2>/dev/null || true"
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $APP_PORT:$APP_PORT --name $APP_CONTAINER_NAME docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA"

  environment:
    name: production
    url: http://$SERVER_IP:$APP_PORT
  only:
    - main